### ISSUE TITLE
this looks exactly what i need

### ISSUE THREAD

**Issue by gcloeval** [jedmao/queso#37]
# Question
Hey your project looks like excatly what I would like to do - have a single source of turth for documentation for a library - in your readme you link to:
https://github.com/jedmao/queso/blob/master/scripts/gen-docs.ts
but this gives a 404 - just wondering can you provide more guideance on how to implement this?

I have a smal llibrary for a few react components, would love to auto-generate all the doz using tsdoc comments or whatever mechanism you came up with? 
Let me know if u have some suggestions cheers, thanks

**Comment by jedmao** [comment]
I fixed the README to point to [`postbuild.ts`](https://github.com/jedmao/queso/blob/master/src/build/postbuild.ts). There's kind of a lot going on, but if you look in the [`src/build`](https://github.com/jedmao/queso/tree/master/src/build) folder, you'll see all the scripts that are related to generating documentation from the TSDoc comments. The most relevant file is probably [`createDoc.ts`](https://github.com/jedmao/queso/blob/master/src/build/createDoc.ts), but it's probably not going to work for you out-of-the-box, because it's written specifically for the functions in this project. I could definitely give it some more features at some point.
